# Generated by Django 4.2.1 on 2023-05-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmenu', '0003_culinary_dish_culinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='foodmenu.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
